[package]
name = "kp2bs58"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"
clap = { version = "3.0.0-rc.7", features = ["derive"] }
serde = "1.0.132"
serde_json = "1.0.73"
